# Site settings
title: Digicratie
email: digicratie@erzatz.info
description: "Révolutions numériques et perspectives sur la démocratie"
baseurl: ""
url: "http://www.erzatz.info" 

# Build settings
markdown: kramdown
permalink: pretty

timezone: America/New_York